### ISSUE TITLE
단어 수정 시 메인에 가끔 수정사항 반영 안되거나 두 개씩 나오는 문제

### ISSUE THREAD

**Issue by nujeyh** [nujeyh/my-dictionary#1]
단어 수정하기 페이지에서 [수정하기] 버튼을 누르면
dispatch 하고, 다시 메인페이지로  돌아가도록 했는데요,
멘토링 시간에 말씀해 주신대로 
수정하기 액션을 보내면 이건 비동기로 처리되기 때문에,
updateDict 는 또 저대로 돌아가서 생기는 문제라고 이해를 했는데 (맞나요...?)
어떻게 고쳐야 할 지 도무지 감이 잡히지 않습니다....
일단 과제는 완성하려고 setTimeout 을 설정했는데 전혀 좋은 방법이 아닌 것 같아요...
도움을 부탁드립니다.....

- src/routes/UpdateWord.js line 56~71

```javascript
// 단어 수정하기
  const updateDict = () => {
    if (isBlank() === true) return;

    dispatch(
      updateDictFB({
        id: wordId.id,
        word: word.current.value,
        meaning: meaning.current.value,
        example: example.current.value,
        translation: translation.current.value,
      })
    );

    setTimeout(() => navigate("/"), 700);
  };
```
- src/redux/modules/dictionary.js line 99~122
```javascript
// 파이어베이스 데이터 수정하기
export const updateDictFB = (dictionary) => {
  return async function (dispatch, getState) {
    const docRef = doc(db, "dictionary", dictionary.id);

    dispatch(isLoaded(false));

    // firebase 데이터 업데이트
    await updateDoc(docRef, {
      word: dictionary.word,
      meaning: dictionary.meaning,
      example: dictionary.example,
      translation: dictionary.translation,
    });

    // store의 현재 state와 같은 id도 수정한다
    const _dictionary = getState().dictionary.list;
    const dictIndex = _dictionary.findIndex((item) => {
      return item.id === dictionary.id;
    });

    dispatch(updateDict(dictIndex));
  };
};
```

**Comment by jihyunan-dev** [comment]
안녕하세요 혜준님:)
`setTimeout`으로 해결하신 내용이 올바른 답은 아닐 수 있지만, 이용할 수 있는 것을 생각하여 당장의 문제를 해결하신 것은 정말 멋집니다😎

결국 제대로 해결하기 위해서는 '**데이터가 파이어스토어에서 수정이 완료됨**'을 기다린 후 페이지가 이동되어야 합니다. 그렇다면 페이지를 이동하는 코드가 아래 부분 뒤에 와야할겁니다:)
```javascript
 await updateDoc(docRef, {
      word: dictionary.word,
      meaning: dictionary.meaning,
      example: dictionary.example,
      translation: dictionary.translation,
    });
```
여기에 일반적인 `react-router-dom`을 사용해서는 제대로 작동하지 않는 것으로 알고 있어서 조금 찾아본 결과 https://github.com/remix-run/react-router/issues/8264#issuecomment-991271554 링크를 찾을 수 있었습니다:)
이 내용은 velopert님의 ['thunk에서 라우터 연결하기'](https://github.com/remix-run/react-router/issues/8264#issuecomment-991271554) 에 있었으나, `react-router-dom`의 버전이 변경되며 작동하지 않는 것으로 확인됩니다.
그래도 어떤 식으로 사용하는지만 velopert님의 설명으로 이해하신 후, 위 깃허브링크에서 `react-router-dom v6`에서의 사용법을 보시면 될 것 같습니다😊

일주일동안 너무 고생하셨습니다! 혜준님 너무 잘만드셔서 구경하며 놀랐습니당:) 
이번 한 주도 힘내세요😁😁

**Comment by nujeyh** [comment]
답변 감사합니다! 어떤 부분이 문제인지 이해했어요! 👍
알려주신 링크들 참고해서 공부하겠습니다!!
